(defun quicksort (vec l r)
  (let ((i l)
		(j r)
		(p (svref vec (round (+ l r) 2))))
	(while (<= i j)
	  (while (< (svref vec i) p) (incf i))
	  (while (> (svref vec j) p) (incf j))
	  (when (<= i j)
		(rotatef (svref vec i) (svref vec j))
		(incf i)
		(decf j)))
	(while (>= (- j l) 1) (quicksort vec l j))
	(while (>= (- r i) 1) (quicksort vec i r)))
  vec)
