(defun selection (lst)
  (if (not lst)
      nil
      (let* ((x (minest lst))
	    (ret (selection (remove x lst))))
	(setf ret (cons x ret)))))

(defun minest (lst)
  (if (= 1 (length lst))
      (car lst)
      (let ((ret (minest (cdr lst)))
	    (x (car lst)))
	(if (< x ret)
	    (setf ret x)
	    (setf ret ret)))))

(defun maxest (lst)
  (if (= 1 (length lst))
      (car lst)
      (let ((ret (maxest (cdr lst)))
	    (x (car lst)))
	(if (> x ret)
	    (setf ret x)
	    (setf ret ret)))))
